### ISSUE TITLE
Redstone automation does not work

### ISSUE THREAD

**Issue by Goldmattress** [Civcraft/FactoryMod#143] opened 2015-08-24 21:37 UTC
All redstone related automation for factories appears to be broken.

**Comment by ProgrammerDan** [comment] 2015-08-24 21:38
Just special factories, or Production Factories as well (e.g. "normal" recipe factories).

**Comment by ProgrammerDan** [comment] 2015-08-24 21:58
Barring new information, appears duplicate of: https://github.com/Civcraft/FactoryMod/issues/120

**Comment by Goldmattress** [comment] 2015-08-24 23:12
it is a duplicate, sorry

**Comment by Goldmattress** [comment] 2015-08-24 23:12
in my defence I did ctrl+f for redstone and found nothing.

**Comment by ProgrammerDan** [comment] 2015-08-25 00:02
No worries, happens!

**Closed by ProgrammerDan** 2015-08-25 00:02 UTC
