### ISSUE TITLE
Redstone circuit no longer working with Factorymod as intended

### ISSUE THREAD

**Issue by Grayyer** [Civcraft/FactoryMod#33] opened 2015-01-21 01:14 UTC
It's an odd issue and is kind of a 2-part problem. I am using a simple redstone circuit that has 1 comparator, 2 repeaters, 4 redstone dust, and 2 levers. 1 lever is attached to the front of the furnace to toggle the factory (factory does not matter for this issue to occur; it happens to every type of factory)

When the comparator is turned on, the redstone pulses and the hoppers do not feed charcoal into the furnace (but the comparator does its job and restarts the factory as it should)

When the comparator is turned off, the redstone is on a constant state of being turned on and the hoppers feed charcoal into the furnace as it should (but the redstone mechanic is turned off, so the factory does not restart itself).

So the problem is either 1 thing, or the other. Below are pictures of the setup. The first week or so of the nether this setup worked perfectly and we processed dozens of DC's of both netherbrick and smoothstone via this method.

http://i.imgur.com/6nOgGDU.png

http://i.imgur.com/juqiQ12.png

**Comment by Grayyer** [comment] 2015-01-26 17:24
Even with the hopper updates and the restoration of item sorters, this issue still persists.

**Comment by ttk2** [comment] 2015-01-26 19:27
Get into it and debug. It might not work exactly the same way.

**Comment by ProgrammerDan** [comment] 2015-05-30 17:08
@Grayyer FactoryMod has changed a lot in the months since you opened this. Can you confirm this is still an issue?

**Comment by rourke750** [comment] 2015-05-30 17:55
God this is old.

**Comment by ProgrammerDan** [comment] 2015-06-29 19:47
Redstone listener is functionally untouched since it was first created. I'll give it a lookover, see if I can still reproduce this and other issues. Go ahead and assign to me.

**Comment by ProgrammerDan** [comment] 2015-06-30 21:45
I got a report from Gray that this is no longer an issue, please close.

**Closed** 2015-06-30 22:52 UTC
Labels: bug, P2 - Needed
