### ISSUE TITLE
Factory Furnaces 

### ISSUE THREAD

**Issue by DarkSylvaer** [Civcraft/FactoryMod#141] opened 2015-08-17 18:15 UTC
It seems like when I start up a factory it goes to work, then when i click with a stick on the chest it tells me it turned off. Then when I try and open the furnace it opens it quickly then closes the UI instantly. Seems like a bug, someone else said they had this problem as well.

**Comment by ProgrammerDan** [comment] 2015-08-17 18:23
Duplicate of #128

For factories that complete really quickly (high tier XP, compactor with a single stack to compact, etc) the furnace close behavior is expected -- basically the block is being "replaced" when the factory "shuts off" and that instantly closes any open UIs associated with the furnace.

The visual artifact is an unresolved regression introduced in a recent Spigot upgrade (1.8.7 I believe).

**Closed by ProgrammerDan** 2015-08-17 18:23 UTC
