### ISSUE TITLE
Anvil enchanting cost limit does not work

### ISSUE THREAD

**Issue by ttk2** [Civcraft/FactoryMod#94] opened 2015-06-12 02:12 UTC
In either setting 

  should_default_anvil_cost: true
  set_default_anvil_cost: 37

does not do anything.

**Comment by ProgrammerDan** [comment] 2015-06-12 02:53
Grah, assign to me, I'll look at this once done mathing, unless someone else is eager to FactoryMod?

**Comment by ProgrammerDan** [comment] 2015-06-12 05:29
@ttk2 The issue is the configuration item is read, but never actually *used*. There is literally no code to do this thing.

Want me to look into building it?

**Comment by drjawa** [comment] 2015-06-12 05:30
I'd appreciate it

**Comment by ProgrammerDan** [comment] 2015-06-12 05:31
Alright. Too tired to do tonight, but will look at it tomorrow night/Saturday.

**Comment by ProgrammerDan** [comment] 2015-06-12 05:46
Digging in a little bit, it *was* here: https://github.com/Civcraft/FactoryMod/commit/87ab0a41578b05110d5b21dd5d478d50c729923e

Someone must have regressed it. We gotta get better at checking for these issues, enforce that developers need to merge or rebase against *current* master before committing.

**Comment by ProgrammerDan** [comment] 2015-06-12 05:48
orrrr, lmao @rourke750 added it then removed it in a later merge-commit https://github.com/Civcraft/FactoryMod/commit/19bde1ca8f853710046f58a93fc19c8cefbb7f76

**Comment by ProgrammerDan** [comment] 2015-06-12 05:51
Lemme see about just uh, re-introducing what rourke wrote. I have no idea if it works as written, or if there was a reason he removed it.

**Comment by ttk2** [comment] 2015-06-12 12:10
We tested it. So I know it works as written. Thanks.

**Comment by erocs** [comment] 2015-06-13 03:44
We gotta get better at checking for these issues, enforce that developers need to merge or rebase against current master before committing

Gerrit is setup. Just need to start funneling all code reviews through it. Of course the barrier of entry would be getting people to push into a non-standard ref.

**Comment by erocs** [comment] 2015-06-13 03:47
Would this affect repair factories as well?

**Comment by ttk2** [comment] 2015-06-13 13:46
no this is totally unrelated to repair factories, in fact this setting will
be disabled and never used again once repair factories are online.

**Comment by ProgrammerDan** [comment] 2015-06-14 03:06
I wonder if that's why rourke removed it, if it was looking like repair
factory was about to go online at the time. #rourkeproblems

**Comment by ttk2** [comment] 2015-06-14 14:11
Yeha its a shame. Dont know why we would change the live FM version though.

**Comment by ProgrammerDan** [comment] 2015-06-14 14:53
Speaking of, did you change config in console on civtest to 
    should_default_anvil_cost: true

Since the patch is merged, I could hop on to test that real quick if you have it set.

**Comment by ttk2** [comment] 2015-06-14 16:24
Yes it is on. But FM on civtest is broken because the io refactor version
wont load without a proper compactor setup in the config.

**Comment by rourke750** [comment] 2015-06-15 21:13
Woops, well I did remove it as there shouldn't have made a difference because I don't believe you can even load the newest factorymod without specifying something in the repair factory config section.

**Comment by ProgrammerDan** [comment] 2015-06-26 17:56
We should just close this, no longer relevant.

**Closed** 2015-06-26 19:39 UTC
Labels: bug, P1 - Critical
